import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Squares from "./components/squares";
import { Client } from "@notionhq/client";

export async function getStaticProps() {
  // Initializing a client
  const notion = new Client({
    auth: process.env.NOTION_TOKEN,
  });
  const { results } = await notion.databases.query({
    database_id: "3d54c96cc6ae48f59030df4de612e5c9",
  });
  const records = results.map((page) => {
    const dt = new Date(page.created_time);
    return dt.getDay();
  });
  console.log(records);
  return { props: { records } };
}

export default function Home({ records }: { records: string[] }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Love Contribution💕</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Love Contribution by<br></br>
          <a href="https://github.com/ichn-hu/">@ichn-hu</a> and{" "}
          <a href="https://github.com/iynewz/">@iynewz</a>
        </h1>
      </main>

      <div className={styles.graph}>
        <ul className={styles.months}>
          <li>Jan</li>
          <li>Feb</li>
          <li>Mar</li>
          <li>Apr</li>
          <li>May</li>
          <li>Jun</li>
          <li>Jul</li>
          <li>Aug</li>
          <li>Sep</li>
          <li>Oct</li>
          <li>Nov</li>
          <li>Dec</li>
        </ul>
        <ul className={styles.days}>
          <li>Sun</li>
          <li>Mon</li>
          <li>Tue</li>
          <li>Wed</li>
          <li>Thu</li>
          <li>Fri</li>
          <li>Sat</li>
        </ul>
        <Squares length={365}></Squares>
      </div>
      <ul>
        {records.map((record) => (
          <li>{record}</li>
        ))}
      </ul>
      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
